<?php
$z[0]=Array("charset","utf-8",0,34);
$z[1]=Array("list","http://www.chinacaipu.com/menu/yaoshanshipu/",34,101);
$z[2]=Array("page","http://www.chinacaipu.com/menu/yaoshanshipu/(*).html ",101,177);
$z[3]=Array("titlerule","<h1 class=\"contit\">[内容]</h1>",177,242);
$z[4]=Array("authorrule","<span class=\"info_txt\">[内容]</a>",242,312);
$z[5]=Array("sourcerule","",312,347);
$z[6]=Array("bodyrule","<div class=\"content\">[内容]</div>",347,413);
$z[7]=Array("fyrule","<span class='current'><u></u>[内容]<u></u>4</a>",413,489);

?>