<a href="/menu/shuichanshipu/70214.html"><img a="http://www.chinacaipu.com/uploads/img/8/71387595814.jpg"><i>[field:title/]</i></a>

        <li class="p5"><a href="/menu/danleishipu/70078.html"><img a="http://www.chinacaipu.com/uploads/img/a/41387595714.jpg"><i>五香茶叶蛋</i></a>

        <li class="p6"><a href="/menu/rouleishipu/70084.html"><img a="http://www.chinacaipu.com/uploads/img/d/101387595526.jpg"><i>香辣豆腐腩肉煲</i></a>

        <li class="p7"><a href="/menu/shandonglucai/70047.html"><img a="http://www.chinacaipu.com/uploads/img/a/41387594822.jpg"><i>大虾烧白菜</i></a>

        <li class="p8"><a href="/menu/hunanmeishi/70035.html"><img a="http://www.chinacaipu.com/uploads/img/8/71385865613.jpg"><i>酸豆角炒牛肉</i></a>

        <li class="p9"><a href="/menu/hunanmeishi/70216.html"><img a="http://www.chinacaipu.com/uploads/img/c/21387596289.jpg"><i>三丝茄子</i></a>

    </ul>

<div class="w980t mt20"><h2>健康养生</h2>

    <div class="tip"><a href="/menu/zhongyiyangsheng">中医养生</a>|<a href="/menu/yundongyangsheng">运动养生</a>|<a href="/menu/yinshiyangsheng">饮食养生</a>|<a href="/menu/renqunyangsheng">人群养生</a></div>

</div>

<div class="w980 clearfix">

    <div class="w330b">

        <div class="w330bt"><h2>中医养生</h2><a href="/menu/zhongyiyangsheng" class="more">更多>></a></div>

                <div class="h126">

                        <a class='hot' href="/menu/tizhiyangsheng/70251.html"><img title="常喝八种茶最能滋阴补肾" a="/d/file/menu/tizhiyangsheng/2013-12-21/7c7b3c86c06319df9bcf09575fcbba65.jpg"></a>

                        <ul class="slist">

                          <li><a href="/menu/zhongyaoyaofang/61806.html">养生保健 5个养生秘方健康长寿</a>

                          <li><a href="/menu/zhongyaojinji/61789.html">不可不知的中药禁忌 喝中药不能吃什么食物</a>

                          <li><a href="/menu/tizhiyangsheng/61577.html">面苍色白是血虚体质的表现 如何调养</a>

                          <li><a href="/menu/zhongyaoyaofang/61758.html">治疗白发的民间偏方</a>

                          <li><a href="/menu/teseliaofa/61494.html">中医教你看“五官气色”知健康</a>

                        </ul>

        </div>

        <ul class="newlist">

                    <li><a href="/menu/teseliaofa/61495.html">针灸美容的好处 适应证广疗效持久</a>

                    <li><a href="/menu/teseliaofa/61471.html">中医拔罐减肥 找准方法和穴位</a>

                    <li><a href="/menu/teseliaofa/61474.html">口干心热烦躁 可刮痧泻心火</a>

                    <li><a href="/menu/zhongyaoyaofang/61773.html">咳嗽偏方 白糖拌鸡蛋治疗咳嗽</a>

                    <li><a href="/menu/teseliaofa/61466.html">秋季嘴唇起皮或许是脾胃有热</a>

                    <li><a href="/menu/teseliaofa/61476.html">秋季上火症状 怎么看是肝火旺</a>

                </ul>



        <div class="w330bt"><h2>运动养生</h2><a href="/menu/yundongyangsheng" class="more">更多>></a></div>

                <div class="h126">

                        <a class='hot' href="/menu/tiyuyundong/68088.html"><img title="有效骑车瘦身法 快速瘦身" a="/d/file/menu/tiyuyundong/2013-12-22/6c098dc3945e78bef190d1574d61a3d1.jpg"></a>

                        <ul class="slist">

                          <li><a href="/menu/yujia/68583.html">简单易学的瘦身减肥瑜伽</a>

                          <li><a href="/menu/youyangyundong/68292.html">游泳耳朵进水怎么办？</a>

                          <li><a href="/menu/youyangyundong/68285.html">冬季游泳注意事项</a>

                          <li><a href="/menu/yujia/68623.html">瑜伽瘦全身的练习方法</a>

                          <li><a href="/menu/yujia/68563.html">练习瑜伽减肥需要注意什么？</a>

                        </ul>

        </div>

        <ul class="newlist">

                    <li><a href="/menu/tiyuyundong/68045.html">常打羽毛球可减肥</a>

                    <li><a href="/menu/youyangyundong/68301.html">游泳减肥小技巧大瘦身</a>

                    <li><a href="/menu/jianshen/68691.html">练习肚皮舞的宜忌事项</a>

                    <li><a href="/menu/jianshen/68673.html">孩子如何快速增高？</a>

                    <li><a href="/menu/jianshen/68680.html">成年人还有没有增高的机会？</a>

                    <li><a href="/menu/taijiquan/68897.html">如何才能练好太极拳？</a>

                </ul>

    </div>

    <div class="w380b">

        <div class="w330bt"><h2>饮食养生</h2><a href="/menu/yinshiyangsheng" class="more">更多>></a></div>

                <div class="h126">

                        <a class='hot' href="/menu/jiankangyingyang/70195.html"><img title="吃水果的7大禁忌，你了解了吗？" a="/d/file/menu/jiankangyingyang/2013-12-21/0a413de33835669e301929cb97977bac.jpg"></a>

                        <ul class="slist">

                          <li><a href="/menu/shicaiyinpin/67526.html">香菇不为人知的保健功效</a>

                          <li><a href="/menu/shicaiyinpin/67517.html">西红柿汁祛痘法  吃掉脸上小斑点</a>

                          <li><a href="/menu/jiankangyingyang/62309.html">味精有5大禁忌切勿盲目食用</a>

                          <li><a href="/menu/jiankangyingyang/62365.html">9大食物巧搭配 追求营养最大化</a>

                          <li><a href="/menu/shicaiyinpin/70010.html">手打贡鱼丸</a>

                        </ul>

        </div>

        <ul class="newlist">

                    <li><a href="/menu/shiliaoshibu/18859.html">治疗风寒感冒食疗方（图）</a>

                    <li><a href="/menu/jiankangyingyang/62285.html">必看！食品包装10大安全警示</a>

                    <li><a href="/menu/jiankangyinshi/31344.html">辣椒越辣 越能抗菌</a>

                    <li><a href="/menu/sijiyinshi/38215.html">初秋养生饮食的四个首选</a>

                    <li><a href="/menu/jiankangyingyang/62296.html">六种错误的饮食小常识</a>

                    <li><a href="/menu/jiankangyingyang/62301.html">健康提醒 深秋饮食四大禁忌</a>

                </ul>



        <div class="w330bt"><h2>疾病预防</h2><a href="/menu/jibingyufang" class="more">更多>></a></div>

                <div class="h126">

                        <a class='hot' href="/menu/aizhengyufang/50604.html"><img title="感冒不好可能是癌症征兆" a="/d/file/menu/aizhengyufang/2013-12-22/2a3193e02242578c206cc65b6754c68a.jpg"></a>

                        <ul class="slist">

                          <li><a href="/menu/fukebing/52137.html">OL久坐危害大 警惕尿道感染</a>

                          <li><a href="/menu/jibinghuli/52440.html">老年人预防心脑血管病吃白果</a>

                          <li><a href="/menu/aizhengyufang/50598.html">乏力贫血 胃癌5信号需重视</a>

                          <li><a href="/menu/pifubing/52863.html">警惕 ！糖尿病易引发皮肤瘙痒</a>

                          <li><a href="/menu/aizhengyufang/50564.html">人体不同器官致癌原因大揭秘</a>

                        </ul>

        </div>

        <ul class="newlist">

                    <li><a href="/menu/aizhengyufang/50566.html">10年后癌症将光临每一个家庭</a>

                    <li><a href="/menu/aizhengyufang/50559.html">警惕，性生活不当也会得癌！</a>

                    <li><a href="/menu/chuanranbing/50609.html">暴雨后：谨防传染病惹身</a>

                    <li><a href="/menu/aizhengyufang/50581.html">女人预防乳腺癌吃哪些食物</a>

                    <li><a href="/menu/aizhengyufang/50583.html">易致癌的男性如何有效防癌</a>

                    <li><a href="/menu/chuanranbing/50612.html">如何预防H7N9禽流感？</a>

                </ul>

    </div>

    <div class="w230b">

        <div class="w208 mt20">

            <h2>人群养生</h2>

                                       <a class="img208" href="/menu/dazhongjiankang/70202.html"><img title="治疗失眠吃这些食物好" a="http://www.chinacaipu.com/uploads/img/c/81387683754.jpg"></a>

                        <ul class="slist">

                            <li><a href="/menu/laonianyangsheng/34356.html">老年人养生从哪些方面做起？</a>

                            <li><a href="/menu/dazhongjiankang/38377.html">涂口红会致胃癌吗</a>

                            <li><a href="/menu/shoushenmeirong/28494.html">油性头发的九大忌食</a>

                            <li><a href="/menu/dazhongjiankang/38401.html">六种牙病的治疗方法</a>

                            <li><a href="/menu/bailingyangsheng/34064.html">八种情绪过度对白领人员的危害</a>

                            <li><a href="/menu/nvxingyangsheng/34250.html">女人吃什么抗衰老效果好呢?</a>

                            <li><a href="/menu/nvxingyangsheng/34086.html">小便用纸巾易患阴道炎</a>

                            <li><a href="/menu/dazhongjiankang/38407.html">秋季干燥咳嗽 吃烤橘子治风寒</a>

                        </ul>

        </div>

        <div class="w208 mt10">

            <h2>白领养生</h2>

                        <div class="h75">

                            <a href="/menu/bailingyangsheng/70039.html"><img title="将吃快餐的危害降低的方法" a="/d/file/menu/dazhongjiankang/2013-11-29/smallcfd7d305faaeb2880d4886a3a4cc17791385698205.jpg"></a>

              <h4><a href="/menu/bailingyangsheng/70039.html">将吃快餐的危害降低的方法</a></h4>

              <p>快节奏的都市生活，迫使上班族们选择快餐以迅速解决自...<a class="read" href="/menu/bailingyangsheng/70039.html">[全文]</a></p>

                          </div>

            <ul class="slist">

                            <li><a href="/menu/bailingyangsheng/34092.html">适合白领的6种营养食物</a>

                            <li><a href="/menu/bailingyangsheng/34117.html">上班族健康用电脑的12个秘笈</a>

                            <li><a href="/menu/shoushenmeirong/28540.html">丰乳健胸与饮食</a>

                            <li><a href="/menu/nvxingyangsheng/34334.html">女性养生还原红润肌肤</a>

                            <li><a href="/menu/shoushenmeirong/28543.html">白嫩皮肤也可以吃出来</a>

                            <li><a href="/menu/bailingyangsheng/34103.html">白领养生 8个时段“忙里偷闲”做保健</a>

                            <li><a href="/menu/nvxingyangsheng/34362.html">女人补血丰胸的四大食谱</a>

                            <li><a href="/menu/nvxingyangsheng/34316.html">女性养生最忌讳的几件事</a>

                        </ul>

        </div>

    </div>

</div>

<div class="w980t mt20"><h2>友情链接</h2></div>

<div class="flink">

     <a href="http://www.chinacaipu.com">菜谱</a>

     <a href="http://food.poco.cn">poco美食网</a>

     <a href="http://www.tangjiu.com">食品招商</a>

     <a href="http://www.szeat.net">深圳饮食网</a>

     <a href="http://suzhou.8684.cn">苏州公交网</a>

     <a href="http://www.tech-food.com">食品科技网</a>

     <a href="http://www.zhms.cn">中华美食</a>

     <a href="http://www.9998.tv">酒招商</a>

     <a href="http://www.spzs.com">食品招商网</a>

     <a href="http://www.spjxcn.com">中国食品设备网</a>

     <a href="http://food.39.net">39健康饮食</a>

     <a href="http://www.tfysw.com">美食城</a>

     <a href="http://www.fancai.com">饭菜网</a>

     <a href="http://health.lady8844.com">爱美网养生</a>

     <a href="http://www.aibang.com">爱帮美食网</a>

     <a href="http://91chihe.shangdu.com">美食网</a>

     <a href="http://www.doodii.com">外卖网</a>

     <a href="http://info.china.alibaba.com/news/community/c5.htm">阿里巴巴食品</a>

     <a href="http://www.lilywed.cn">婚宴酒店</a>

     <a href="http://eat.sz.net.cn">美食天下菜谱</a>

     <a href="http://ys.99.com.cn">食谱大全</a>

     <a href="http://www.tripc.net">启程旅游网</a>

     <a href="http://www.fumuhui.com">父母会育儿网</a>

     <a href="http://www.loach.net.cn">中国食谱网</a>

     <a href="http://www.fantong.com">饭统网</a>

     <a href="http://www.jiameng.com">加盟</a>

     <a href="http://www.bianzhirensheng.com">编织人生</a>

     <a href="http://www.hao123.com">hao123</a>

     <a href="http://ys.99.com.cn">饮食健康</a>

 </div>

<script src="{dede:field name='templeturl'