<?php
$z[0]=Array("imglink","",0,16);
$z[1]=Array("filename","",40,57);
$z[2]=Array("title","",59,73);
$z[3]=Array("info","",89,102);
$z[4]=Array("imglink","",328,344);
$z[5]=Array("filename","",368,385);
$z[6]=Array("title","",387,401);
$z[7]=Array("info","",417,430);
$z[8]=Array("imglink","",14253,14269);
$z[9]=Array("filename","",14287,14304);
$z[10]=Array("title","",14306,14320);
$z[11]=Array("info","",14336,14349);

?>