<?php
$z[0]=Array("charset","utf-8",0,34);
$z[1]=Array("list","http://www.chinacaipu.com/menu/dazhongjiankang/",34,104);
$z[2]=Array("page","http://www.chinacaipu.com/menu/dazhongjiankang/(*).html",104,182);
$z[3]=Array("titlerule","<h1 class=\"contit\">[内容]</h1>",182,247);
$z[4]=Array("authorrule","<span class=\"info_txt\">[内容]</a>",247,317);
$z[5]=Array("sourcerule","",317,352);
$z[6]=Array("bodyrule","<div class=\"content\">[内容]</div>",352,418);
$z[7]=Array("fyrule","<span class='current'><u></u>[内容]<u></u>4</a>",418,494);

?>