<?php
$z[0]=Array("charset","utf-8",0,34);
$z[1]=Array("list","http://www.chinacaipu.com/menu/dianxinshipin",34,101);
$z[2]=Array("page","http://www.chinacaipu.com/menu/dianxinshipin/(*).html",101,177);
$z[3]=Array("titlerule","<h1 class=\"contit\">[内容]</h1>",177,242);
$z[4]=Array("authorrule","<span class=\"info_txt\">作者：[内容]</a>",242,321);
$z[5]=Array("sourcerule","",321,356);
$z[6]=Array("bodyrule","<div class=\"content\">[内容]</div>",356,422);
$z[7]=Array("fyrule","",422,449);

?>