<p>  


      <a href="[field:arcurl/]" class="pic"><img src="[field:litpic/]" alt="[field:title function='html2text(@me)'/]"/></a>
					<a href="[field:arcurl/]" class="title">[field:title/]</a>
					<span class="date"><small>最后更新：</small>[field:pubdate function="GetDateMK(@me)"/]</span>

         </p>


    </div>


    <div class="page"> <span class=disabled><u></u>上一页</span><span class='current'><u></u>1</span><a title='第2页' href='/menu/jiachangcaipu/index_2.html' target='_self'><u></u>2</a><a title='第3页' href='/menu/jiachangcaipu/index_3.html' target='_self'><u></u>3</a><a title='第4页' href='/menu/jiachangcaipu/index_4.html' target='_self'><u></u>4</a><a title='第5页' href='/menu/jiachangcaipu/index_5.html' target='_self'><u></u>5</a><a title='第6页' href='/menu/jiachangcaipu/index_6.html' target='_self'><u></u>6</a><a title='第7页' href='/menu/jiachangcaipu/index_7.html' target='_self'><u></u>7</a><a title='上一页' href='/menu/jiachangcaipu/index_2.html' target='_self'><u></u>下一页</a> </div>


    <div class="w640t">


      <h2>大家都在看</h2>


    </div>


    <div class="cppic">


      <p>


                <a href="/menu/dongbeifengwei/1668.html"><img src="style/images/ebbe8e1b1e8027cad056b0bd6c658599.jpg" alt="猪肉炖粉条(7)">猪肉炖粉条(7)</a>


                <a href="/menu/jingcaishipu/69853.html"><img src="style/images/ed93f4bda92a1dccda8c872864014579.jpg" alt="椒盐炸茄盒儿">椒盐炸茄盒儿</a>


                <a href="/menu/hanguoliaoli/27498.html"><img src="style/images/856ea746618feddd450af0722c7f53d3.jpg" alt="韩式炒年糕(2)">韩式炒年糕(2)</a>


                <a href="/menu/rouleishipu/29645.html"><img src="style/images/953ddae1185fe9c1904b2359c72e984d.jpg" alt="辣炒排骨">辣炒排骨</a>


                <a href="/menu/sichuanfengwei/69931.html"><img src="style/images/904a36f3f2837639f5a1603d2f7ca4cf.jpg" alt="毛血旺">毛血旺</a>


                <a href="/menu/guangdongecai/69854.html"><img src="style/images/2eba96e9b664c529a49bbad4535e3498.jpg" alt="腊肠煲仔饭">腊肠煲仔饭</a>


                <a href="/menu/dongbeifengwei/69869.html"><img src="style/images/small7a4d3f5ad2d8e91aa3269e441e85e0e11384742218.jpg" alt="酸菜鱿鱼">酸菜鱿鱼</a>


                <a href="/menu/shanghaimeishi/6427.html"><img src="style/images/f5e7c47c5f6bfe82b7a767c599068652.jpg" alt="清蒸蟹粉狮子头的做法">清蒸蟹粉狮子头的做法</a>


              </p>


    </div>


    <div class="bottom_640X90"> 


      <script src="style/js/ad_nei_taobao_640X90.js"></script> 


    </div>


    <div class="ft_ad_640*200"> 


      <script type="text/javascript" src="style/js/ad_nei_baidu_dibu_yun.js"></script>


  </div>


</div>


<div class="w300">


        <div class="ad300">


                  <script src="style/js/ad_nei_baidu_300X250_1.js"></script>


                </div>


        <h2 class="w300h2">热门食材</h2>


        <div class="rmsc">


                        <a href="http://www.chinacaipu.com/zhuanti/guojiang.html">果酱</a>


                        <a href="http://www.chinacaipu.com/zhuanti/huangguajidan.html">黄瓜鸡蛋</a>


                        <a href="http://www.chinacaipu.com/zhuanti/doufuyu.html">豆腐鱼</a>


                        <a href="http://www.chinacaipu.com/zhuanti/niuroufanqie.html">牛肉番茄</a>


                        <a href="http://www.chinacaipu.com/html/zhuanti547.html">饼干</a>


                        <a href="http://www.chinacaipu.com/html/zhuanti158.html">番茄</a>


                        <a href="http://www.chinacaipu.com/html/zhuanti141.html">土豆</a>


                        <a href="http://www.chinacaipu.com/html/zhuanti140.html">茄子</a>


                        <a href="http://www.chinacaipu.com/html/zhuanti139.html">排骨</a>


                        <a href="http://www.chinacaipu.com/html/zhuanti137.html">萝卜</a>


                    </div>


        <h2 class="w300h2">专题推荐</h2>


        <ul class="zttj">


                                     <li><a href="http://www.chinacaipu.com/html/zhuanti143.html">黄瓜的做法</a><a href="http://www.chinacaipu.com/html/zhuanti101.html">蛋糕的做法</a><a href="http://www.chinacaipu.com/html/zhuanti73.html">鸡蛋的做法</a><a href="http://www.chinacaipu.com/html/zhuanti68.html">火锅的做法</a>                        <li><a href="http://www.chinacaipu.com/html/zhuanti20.html">鸡翅的做法</a><a href="http://www.chinacaipu.com/html/zhuanti18.html">土豆的做法</a><a href="http://www.chinacaipu.com/html/zhuanti16.html">排骨的做法</a><a href="http://www.chinacaipu.com/html/zhuanti15.html">牛肉的做法</a>                        <li><a href="http://www.chinacaipu.com/html/zhuanti12.html">鸡的做法</a><a href="http://www.chinacaipu.com/zhuanti/doufu.html">豆腐的做法</a>                    </ul>


        <div class="ztpic">


            <ul>


                                                <li>


                                        <a href="/menu/dazhongjiankang/70169.html"><img src="style/images/9d0f1219e254715a644712777ec100af.jpg" title="这样喝水，可以治百病"></a>


                    <h3><span class="cr">常识</span><a href="/menu/dazhongjiankang/70169.html">这样喝水，可以治百病</a></h3>


                    <p>


                                           <a href="/menu/shicaiyinpin/65841.html">吃鸡蛋的十大错误常识</a>


                                           <a href="/menu/jiankangyingyang/62342.html">幼儿饮食常识</a>


                                           <a href="/menu/bailingyangsheng/34120.html">如何排毒养颜呢</a>


                                           <a href="/menu/jianshen/68694.html">正确的仰卧起坐</a>


                                          </p>


                </li>


                                <li>


                                        <a href="/menu/shoushenmeirong/70180.html"><img src="style/images/fa5324a150440dcbe5b4dda9811abeb5.jpg" title="7种水果帮你减掉腰腹赘肉"></a>


                    <h3><span class="cy">美容</span><a href="/menu/shoushenmeirong/70180.html">7种水果帮你减掉腰腹赘肉</a></h3>


                    <p>


                                           <a href="/menu/shoushenmeirong/28497.html">这些食物会使你皮肤白皙</a>


                                           <a href="/menu/nvxingyangsheng/34362.html">丰胸的四大食谱</a>


                                           <a href="/menu/nvxingyangsheng/34295.html">女性养生饮食</a>


                                           <a href="/menu/nvxingyangsheng/34234.html">女人如何养生？</a>


                                          </p>


                </li>


                                <li>


                                        <a href="/menu/muyingbaojian/35220.html"><img src="style/images/ffdede53a5bbe9c1fe89b10350d57650.jpg" title="宝宝晚上睡觉踢被子8大原因"></a>


                    <h3><span class="cg">母婴</span><a href="/menu/muyingbaojian/35220.html">宝宝晚上睡觉踢被子8大原因</a></h3>


                    <p>


                                           <a href="/menu/haizijiankang/8918.html">调理感冒宝宝</a>


                                           <a href="/menu/ertongshipin/18887.html">新手妈妈DIY辅食诀窍</a>


                                           <a href="/menu/haizijiankang/8751.html">使孩子聪明的食物</a>


                                           <a href="/menu/yunyingbaojian/8443.html">催奶汤</a>


                                          </p>


                </li>


                            </ul>


        </div>


        <div class="ad300 mt20"><script src="style/js/ad_nei_baidu_300X250_2.js"></script></div>


        <h2 class="w300h2">热门推荐</h2>


        <div class="rmtj">


            <ul>


                                <li>


                    <a href="/menu/jingcaishipu/69853.html"><img src="style/images/ed93f4bda92a1dccda8c872864014579.jpg" alt="椒盐炸茄盒儿" title="椒盐炸茄盒儿" /></a>


                    <h3><a href="/menu/jingcaishipu/69853.html">椒盐炸茄盒儿</a></h3>


                    <p>椒盐炸茄盒儿炸茄盒儿是一道京味传统美食，茄子切成茄夹塞以肉馅，外面裹上面糊炸制而成，除了外酥里软的美...<a class="read" href="/menu/jingcaishipu/69853.html">[全文]</a></p>


                                <li>


                    <a href="/menu/shuichanshipu/69903.html"><img src="style/images/774dd8e297a0602238db10f8cd623fb4.jpg" alt="葱香油爆虾" title="葱香油爆虾" /></a>


                    <h3><a href="/menu/shuichanshipu/69903.html">葱香油爆虾</a></h3>


                    <p>油爆虾通常选用中小型虾，用旺火菜籽油锅炸虾，烧好后虾外脆内嫩。加上葱香萦绕，口口鲜嫩。具有通乳调理，...<a class="read" href="/menu/shuichanshipu/69903.html">[全文]</a></p>


                                <li>


                    <a href="/menu/hunanmeishi/70022.html"><img src="style/images/6591079002726a73e3cf7aa08c3b34dc.jpg" alt="荷香小炒肉" title="荷香小炒肉" /></a>


                    <h3><a href="/menu/hunanmeishi/70022.html">荷香小炒肉</a></h3>


                    <p>   导读：今天介绍给大家的小炒肉，祖籍是湖南省，但因为其肉质鲜嫩、油香而不腻、集酸辣鲜香于一身，又...<a class="read" href="/menu/hunanmeishi/70022.html">[全文]</a></p>


                            </ul>


        </div>


        <div class="w300t"><h2>热门食谱</h2></div>


        <div class="rmsc">


                      <a href="/menu/rouleishipu/29485.html">鱼香肉丝</a>


                      <a href="/menu/danleishipu/369.html">乡巴佬卤蛋</a>


                      <a href="/menu/rouleishipu/29209.html">蒜香排骨</a>


                      <a href="/menu/sushishipu/3792.html">铁板豆腐</a>


                      <a href="/menu/qinleishipu/2064.html">白斩鸡</a>


                      <a href="/menu/qinleishipu/1875.html">栗子烧鸡翅</a>


                      <a href="/menu/bingzi/29103.html">葱油饼</a>


                      <a href="/menu/sushishipu/10232.html">干锅土豆</a>


                      <a href="/menu/sushishipu/10127.html">老干妈土豆块</a>


                      <a href="/menu/baozi/17137.html">鲜肉包子</a>


                      <a href="/menu/rouleishipu/33258.html">酱大骨</a>


                      <a href="/menu/qinleishipu/12153.html">土豆烧鸡</a>


                      <a href="/menu/rouleishipu/29426.html">蒜香蜜汁叉烧肉</a>


                      <a href="/menu/sushishipu/10133.html">豆豉辣豆腐</a>


                      <a href="/menu/rouleishipu/33272.html">土豆片烤辣五花</a>


                      <a href="/menu/rouleishipu/32504.html">香辣酱香骨</a>


                      <a href="/menu/qinleishipu/7425.html">蜜汁酱烤鸭腿</a>


                      <a href="/menu/jingcaishipu/6459.html">奶酪肘子</a>


                  </div>


       <script src='style/js/ad_nei_baidu_yun_300X250.js'></script>


        <h2 class="w300h2">美食图片</h2>


        <div class="mstp clearfix">


            <p>


                          <a href="/menu/hunanmeishi/70185.html"><img src="style/images/6a1104d61a5f6579efb2e3d30096074e.jpg"><i>小炒河虾</i></a>


                          <a href="/menu/hainanshipu/70105.html"><img src="style/images/7c1bf9f86775fe8bcd152c52d7a85016.jpg"><i>蒜泥拌炖肉</i></a>


                          <a href="/menu/zhecai/69917.html"><img src="style/images/c1eb4dd70ae8adda9a02728b8df11508.jpg"><i>荷叶粉蒸肉</i></a>


                          <a href="/menu/fujianmeishi/70090.html"><img src="style/images/61931f12e3ec66984375ac0f564d657d.jpg"><i>炸糟鱼</i></a>


                         </p>


        </div>


        <div class="ad300 mt20"><script src="style/js/ad_nei_baidu_300X250_3.js"></script></div>


        <!--height85-->


        <div style="height:85px"></div>


    </div>


</div>


<script src="{dede:field name='templeturl'