<?php
$z[0]=Array("charset","utf-8",0,34);
$z[1]=Array("list","http://www.chinacaipu.com/menu/tianjinmeishi/index_2.html",34,114);
$z[2]=Array("page","http://www.chinacaipu.com/menu/tianjinmeishi/(*).html",114,190);
$z[3]=Array("titlerule","<h1 class=\"contit\">[内容]</h1>",190,255);
$z[4]=Array("authorrule","",255,290);
$z[5]=Array("sourcerule","",290,325);
$z[6]=Array("bodyrule","<div class=\"content\">[内容]</div>",325,391);
$z[7]=Array("fyrule","<span class='current'><u></u>[内容]<u></u>7</a>",391,467);

?>