<?php
$z[0]=Array("charset","utf-8",0,34);
$z[1]=Array("list","http://www.chinacaipu.com/menu/tangbaozhoushipu/index_2.html",34,117);
$z[2]=Array("page","http://www.chinacaipu.com/menu/tangbaozhoushipu/(*).html",117,196);
$z[3]=Array("titlerule","<h1 class=\"contit\">[内容]</h1>",196,261);
$z[4]=Array("authorrule","",261,296);
$z[5]=Array("sourcerule","",296,331);
$z[6]=Array("bodyrule","<div class=\"content\">[内容]</div>",331,397);
$z[7]=Array("fyrule","",397,424);

?>