<?php
$z[0]=Array("charset","utf-8",0,34);
$z[1]=Array("list","http://www.chinacaipu.com/menu/hanguoliaoli/",34,101);
$z[2]=Array("page","http://www.chinacaipu.com/menu/hanguoliaoli/(*).html",101,176);
$z[3]=Array("titlerule","<h1 class=\"contit\">[内容]</h1>",176,241);
$z[4]=Array("authorrule","",241,276);
$z[5]=Array("sourcerule","",276,311);
$z[6]=Array("bodyrule","<div class=\"content\">[内容]</div>",311,377);
$z[7]=Array("fyrule","<span class='current'><u></u>[内容]<u></u>4</a>",377,453);

?>