<?php
$z[0]=Array("charset","utf-8",0,34);
$z[1]=Array("list","http://www.chinacaipu.com/menu/ertongshipin/index.html",34,111);
$z[2]=Array("page","http://www.chinacaipu.com/menu/ertongshipin/(*).html",111,186);
$z[3]=Array("titlerule","<h1 class=\"contit\">[内容]</h1>",186,251);
$z[4]=Array("authorrule","<span class=\"info_txt\">[内容]</a>",251,321);
$z[5]=Array("sourcerule","",321,356);
$z[6]=Array("bodyrule","<div class=\"content\">[内容]</div>",356,422);
$z[7]=Array("fyrule","<span class='current'><u></u>[内容]<u></u>4</a>",422,498);

?>