<?php
$z[0]=Array("charset","utf-8",0,34);
$z[1]=Array("list","http://www.chinacaipu.com/menu/nvxingbaojian/",34,102);
$z[2]=Array("page","http://www.chinacaipu.com/menu/nvxingbaojian/(*).html",102,178);
$z[3]=Array("titlerule","<h1 class=\"contit\">[内容]</h1>",178,243);
$z[4]=Array("authorrule","<span class=\"info_txt\">[内容]</a>",243,313);
$z[5]=Array("sourcerule","",313,348);
$z[6]=Array("bodyrule","<div class=\"content\">[内容]</div>",348,414);
$z[7]=Array("fyrule","<span class='current'><u></u>[内容]<u></u>4</a>",414,490);

?>