<?php
$z[0]=Array("charset","utf-8",0,34);
$z[1]=Array("list","http://www.chinacaipu.com/menu/liangbancai/",34,100);
$z[2]=Array("page","http://www.chinacaipu.com/menu/liangbancai/(*).html",100,174);
$z[3]=Array("titlerule","<h1 class=\"contit\">[内容]</h1>",174,239);
$z[4]=Array("authorrule","<span class=\"info_txt\">作者：[内容]</a>",239,318);
$z[5]=Array("sourcerule","",318,353);
$z[6]=Array("bodyrule","<div class=\"content\">[内容]</div>",353,419);
$z[7]=Array("fyrule","<span class='current'><u></u>[内容]<u></u>4</a>",419,495);

?>