<?php
$z[0]=Array("charset","utf-8",0,34);
$z[1]=Array("list","http://www.chinacaipu.com/menu/tusi/",34,93);
$z[2]=Array("page","http://www.chinacaipu.com/menu/tusi/(*).html",93,160);
$z[3]=Array("titlerule","<h1 class=\"contit\">[内容]</h1>",160,225);
$z[4]=Array("authorrule","",225,260);
$z[5]=Array("sourcerule","",260,295);
$z[6]=Array("bodyrule","<div class=\"content\">[内容]</div>",295,361);
$z[7]=Array("fyrule","<span class='current'><u></u>[内容]<u></u>4</a>",361,437);

?>