<?php
$z[0]=Array("charset","utf-8",0,34);
$z[1]=Array("list","http://www.chinacaipu.com/menu/mianbao",34,95);
$z[2]=Array("page","http://www.chinacaipu.com/menu/mianbao/(*).html",95,165);
$z[3]=Array("titlerule","<h1 class=\"contit\">[内容]</h1>",165,230);
$z[4]=Array("authorrule","",230,265);
$z[5]=Array("sourcerule","",265,300);
$z[6]=Array("bodyrule","<div class=\"content\">[内容]</div>",300,366);
$z[7]=Array("fyrule","<span class='current'><u></u>[内容]<u></u>4</a>",366,442);

?>