<?php
$z[0]=Array("charset","utf-8",0,34);
$z[1]=Array("list","http://www.chinacaipu.com/menu/baozi/",34,94);
$z[2]=Array("page","http://www.chinacaipu.com/menu/baozi/(*).html",94,162);
$z[3]=Array("titlerule","<h1 class=\"contit\">[内容]</h1>",162,227);
$z[4]=Array("authorrule","",227,262);
$z[5]=Array("sourcerule","",262,297);
$z[6]=Array("bodyrule","<div class=\"content\">[内容]</div>",297,363);
$z[7]=Array("fyrule","<span class='current'><u></u>[内容]<u></u>4</a>",363,439);

?>