<?php
$z[0]=Array("charset","utf-8",0,34);
$z[1]=Array("list","http://www.chinacaipu.com/menu/yunnanmeishi",34,100);
$z[2]=Array("page","http://www.chinacaipu.com/menu/yunnanmeishi/(*).html",100,175);
$z[3]=Array("titlerule","<h1 class=\"contit\">[内容]</h1>",175,240);
$z[4]=Array("authorrule","<span class=\"info_txt\">作者：[内容]</a>",240,319);
$z[5]=Array("sourcerule","",319,354);
$z[6]=Array("bodyrule","<div class=\"content\">[内容]</div>",354,420);
$z[7]=Array("fyrule","",420,447);

?>