<?php
$z[0]=Array("charset","utf-8",0,34);
$z[1]=Array("list","http://www.chinacaipu.com/menu/yunyingbaojian/",34,103);
$z[2]=Array("page","http://www.chinacaipu.com/menu/yunyingbaojian/8445.html",103,181);
$z[3]=Array("titlerule","<h1 class=\"contit\">[内容]</h1>",181,246);
$z[4]=Array("authorrule","<span class=\"info_txt\">[内容]</a>",246,316);
$z[5]=Array("sourcerule","",316,351);
$z[6]=Array("bodyrule","<div class=\"content\">[内容]</div>",351,417);
$z[7]=Array("fyrule","<span class='current'><u></u>[内容]<u></u>4</a>",417,493);

?>