<?php
$z[0]=Array("charset","utf-8",0,34);
$z[1]=Array("list","http://www.chinacaipu.com/menu/tushuoyangshen",34,102);
$z[2]=Array("page","http://www.chinacaipu.com/menu/tushuoyangshen(*).html",102,178);
$z[3]=Array("titlerule","<h1 class=\"contit\">[内容]</h1>",178,243);
$z[4]=Array("authorrule","<span class=\"info_txt\">作者：[内容]</a>",243,322);
$z[5]=Array("sourcerule","",322,357);
$z[6]=Array("bodyrule","<div class=\"content\">[内容]</div>",357,423);
$z[7]=Array("fyrule","<span class='current'><u></u>[内容]<u></u>4</a>",423,499);

?>