<?php
$z[0]=Array("charset","utf-8",0,34);
$z[1]=Array("list","http://www.chinacaipu.com/menu/meishi/",34,95);
$z[2]=Array("page","http://www.chinacaipu.com/menu/meishi/(*).html",95,164);
$z[3]=Array("titlerule","<h1 class=\"contit\">[内容]</h1>",164,229);
$z[4]=Array("authorrule","<span class=\"info_txt\">[内容]</a>",229,299);
$z[5]=Array("sourcerule","",299,334);
$z[6]=Array("bodyrule","<div class=\"content\">[内容]</div>",334,400);
$z[7]=Array("fyrule","<span class='current'><u></u>[内容]<u></u>4</a>",400,476);

?>