<a class="pic" href="/menu/dazhongjiankang/38414.html"><img src="style/images/small5e5ee50477888b175c29cfb930a3079a1383838506.jpg" alt="适量补钙 有助头发健康生长">补钙有助头发生长</a>


             <ul class="newlist">


                                      <li> [field:array runphp='yes']@me = (empty(@me['litpic']) ? "" : "<a href='{@me['arcurl']}' class='preview'><img src='{@me['litpic']}'/></a>"); [/field:array]
     [<b>[field:typelink/]</b>] <a href="[field:arcurl/]" class="title">[field:title/]</a> <span class="info"> <small>日期：</small>[field:pubdate function="GetDateTimeMK(@me)"/] <small>点击：</small>[field:click/] <small>好评：</small>[field:scores/] </span>
     <p class="intro"> [field:description/]... </p>
    </li>