<?php
$z[0]=Array("charset","utf-8",0,34);
$z[1]=Array("list","http://www.chinacaipu.com/menu/pengrenqiaomen/",34,103);
$z[2]=Array("page","http://www.chinacaipu.com/menu/pengrenqiaomen/(*).html",103,180);
$z[3]=Array("titlerule","<h1 class=\"contit\">[内容]</h1>",180,245);
$z[4]=Array("authorrule","<span class=\"info_txt\">[内容]</a>",245,315);
$z[5]=Array("sourcerule","",315,350);
$z[6]=Array("bodyrule","<div class=\"content\">[内容]</div>",350,416);
$z[7]=Array("fyrule","<span class='current'><u></u>[内容]<u></u>4</a>",416,492);

?>