<?php
$z[0]=Array("charset","utf-8",0,34);
$z[1]=Array("list","http://www.chinacaipu.com/menu/ca/",34,91);
$z[2]=Array("page","http://www.chinacaipu.com/menu/ca/(*).html",91,156);
$z[3]=Array("titlerule","<h1 class=\"contit\">[内容]</h1>",156,221);
$z[4]=Array("authorrule","<span class=\"info_txt\">[内容]</a>",221,291);
$z[5]=Array("sourcerule","",291,326);
$z[6]=Array("bodyrule","<div class=\"content\">[内容]</div>",326,392);
$z[7]=Array("fyrule","<span class='current'><u></u>[内容]<u></u>4</a>",392,468);

?>