<?php
$z[0]=Array("charset","utf-8",0,34);
$z[1]=Array("list","http://www.chinacaipu.com/menu/taiwancai/index_2.html",34,110);
$z[2]=Array("page","http://www.chinacaipu.com/menu/taiwancai/(*).html",110,182);
$z[3]=Array("titlerule","<h1 class=\"contit\">[内容]</h1>",182,247);
$z[4]=Array("authorrule","",247,282);
$z[5]=Array("sourcerule","",282,317);
$z[6]=Array("bodyrule","<div class=\"content\">[内容]</div>",317,383);
$z[7]=Array("fyrule","<span class='current'><u></u>[内容]<u></u>7</a>",383,459);

?>