<?php
$z[0]=Array("charset","utf-8",0,34);
$z[1]=Array("list","http://www.chinacaipu.com/menu/sushishipu/index_2.html",34,111);
$z[2]=Array("page","http://www.chinacaipu.com/menu/sushishipu/(*).html",111,184);
$z[3]=Array("titlerule","<h1 class=\"contit\">[内容]</h1>",184,249);
$z[4]=Array("authorrule","",249,284);
$z[5]=Array("sourcerule","",284,319);
$z[6]=Array("bodyrule","<div class=\"content\">[内容]</div>",319,385);
$z[7]=Array("fyrule","",385,412);

?>