<?php
$z[0]=Array("charset","utf-8",0,34);
$z[1]=Array("list","http://www.chinacaipu.com/menu/anhuimeishi",34,99);
$z[2]=Array("page","http://www.chinacaipu.com/menu/anhuimeishi/(*).html",99,173);
$z[3]=Array("titlerule","<h1 class=\"contit\">[内容]</h1>",173,238);
$z[4]=Array("authorrule","<span class=\"info_txt\">作者：[内容]</a>",238,317);
$z[5]=Array("sourcerule","",317,352);
$z[6]=Array("bodyrule","<div class=\"content\">[内容]</div>",352,418);
$z[7]=Array("fyrule","",418,445);

?>