<?php
$z[0]=Array("charset","utf-8",0,34);
$z[1]=Array("list","http://www.chinacaipu.com/menu/dangao",34,94);
$z[2]=Array("page","http://www.chinacaipu.com/menu/dangao/(*).html",94,163);
$z[3]=Array("titlerule","<h1 class=\"contit\">[内容]</h1>",163,228);
$z[4]=Array("authorrule","",228,263);
$z[5]=Array("sourcerule","",263,298);
$z[6]=Array("bodyrule","<div class=\"content\">[内容]</div>",298,364);
$z[7]=Array("fyrule","<span class='current'><u></u>[内容]<u></u>7</a>",364,440);

?>