<?php
$z[0]=Array("charset","utf-8",0,34);
$z[1]=Array("list","http://www.chinacaipu.com/menu/rouleishipu/index_[2-3].html",34,116);
$z[2]=Array("page","http://www.chinacaipu.com/menu/rouleishipu/(*).html",116,190);
$z[3]=Array("titlerule","<h1 class=\"contit\">[内容]</h1>",190,255);
$z[4]=Array("authorrule","",255,290);
$z[5]=Array("sourcerule","",290,325);
$z[6]=Array("bodyrule","<div class=\"content\">[内容]</div>\n",325,392);
$z[7]=Array("fyrule","<span class=disabled>[内容]</div>\n",392,455);

?>