<?php
$z[0]=Array("charset","utf-8",0,34);
$z[1]=Array("list","http://www.chinacaipu.com/menu/huoguodiliaojipeifang/index_2.html",34,122);
$z[2]=Array("page","http://www.chinacaipu.com/menu/huoguodiliaojipeifang/(*).html",122,206);
$z[3]=Array("titlerule","<h1 class=\"contit\">[内容]</h1>",206,271);
$z[4]=Array("authorrule","",271,306);
$z[5]=Array("sourcerule","",306,341);
$z[6]=Array("bodyrule","<div class=\"content\">[内容]</div>",341,407);
$z[7]=Array("fyrule","<span class='current'><u></u>[内容]<u></u>7</a>",407,483);

?>