<?php
$z[0]=Array("charset","utf-8",0,34);
$z[1]=Array("list","http://www.chinacaipu.com/menu/sushishipu/",34,99);
$z[2]=Array("page","http://www.chinacaipu.com/menu/sushishipu/(*).html",99,172);
$z[3]=Array("titlerule","<h1 class=\"contit\">[内容]</h1>",172,237);
$z[4]=Array("authorrule","<span class=\"info_txt\">作者：[内容]</a>",237,316);
$z[5]=Array("sourcerule","",316,351);
$z[6]=Array("bodyrule","<span class='current'><u></u>[内容]<u></u>4</a>",351,431);
$z[7]=Array("fyrule","",431,458);

?>