<?php
$z[0]=Array("charset","utf-8",0,34);
$z[1]=Array("list","http://www.chinacaipu.com/menu/aizhengyufang/",34,102);
$z[2]=Array("page","http://www.chinacaipu.com/menu/aizhengyufang//(*).html",102,179);
$z[3]=Array("titlerule","<h1 class=\"contit\">[内容]</h1>",179,244);
$z[4]=Array("authorrule","<span class=\"info_txt\">[内容]</a>",244,314);
$z[5]=Array("sourcerule","",314,349);
$z[6]=Array("bodyrule","<div class=\"content\">[内容]</div>",349,415);
$z[7]=Array("fyrule","<span class='current'><u></u>[内容]<u></u>4</a>",415,491);

?>