<?php
$z[0]=Array("charset","utf-8",0,34);
$z[1]=Array("list","http://www.chinacaipu.com/menu/tangbaozhoushipu/",34,105);
$z[2]=Array("page","http://www.chinacaipu.com/menu/tangbaozhoushipu/(*).html",105,184);
$z[3]=Array("titlerule","<h1 class=\"contit\">[内容]</h1>",184,249);
$z[4]=Array("authorrule","<span class=\"info_txt\">作者：[内容]</a>",249,328);
$z[5]=Array("sourcerule","",328,363);
$z[6]=Array("bodyrule","<div class=\"content\">[内容]</div>",363,429);
$z[7]=Array("fyrule","<span class='current'><u></u>[内容]<u></u>4</a>",429,505);

?>