<?php
$z[0]=Array("charset","utf-8",0,34);
$z[1]=Array("list","http://www.chinacaipu.com/menu/mimianzhushi/index_2.html",34,113);
$z[2]=Array("page","http://www.chinacaipu.com/menu/mimianzhushi/(*).html",113,188);
$z[3]=Array("titlerule","<h1 class=\"contit\">[内容]</h1>",188,253);
$z[4]=Array("authorrule","",253,288);
$z[5]=Array("sourcerule","",288,323);
$z[6]=Array("bodyrule","<div class=\"content\">[内容]</div>",323,389);
$z[7]=Array("fyrule","<span class='current'><u></u>[内容]<u></u>7</a>",389,465);

?>