<?php
$z[0]=Array("charset","utf-8",0,34);
$z[1]=Array("list","http://www.chinacaipu.com/menu/dongbeifengwei/index_2.html",34,115);
$z[2]=Array("page","http://www.chinacaipu.com/menu/dongbeifengwei/(*).html",115,192);
$z[3]=Array("titlerule","<h1 class=\"contit\">[内容]</h1>",192,257);
$z[4]=Array("authorrule","",257,292);
$z[5]=Array("sourcerule","",292,327);
$z[6]=Array("bodyrule","<div class=\"content\">[内容]</div>",327,393);
$z[7]=Array("fyrule","<span class='current'><u></u>[内容]<u></u>7</a>",393,469);

?>