<?php
$z[0]=Array("charset","utf-8",0,34);
$z[1]=Array("list","http://www.chinacaipu.com/menu/rouleishipu/index_[2-3].html",34,116);
$z[2]=Array("page","http://www.chinacaipu.com/menu/rouleishipu/(*).html",116,190);
$z[3]=Array("titlerule","",190,223);
$z[4]=Array("authorrule","",223,258);
$z[5]=Array("sourcerule","",258,293);
$z[6]=Array("bodyrule","",293,324);
$z[7]=Array("fyrule","",324,351);

?>