<?php
$z[0]=Array("charset","utf-8",0,34);
$z[1]=Array("list","http://www.chinacaipu.com/menu/teseliaofa/",34,99);
$z[2]=Array("page","http://www.chinacaipu.com/menu/teseliaofa/(*).html",99,172);
$z[3]=Array("titlerule","<h1 class=\"contit\">[内容]</h1>",172,237);
$z[4]=Array("authorrule","<span class=\"info_txt\">[内容]</a>",237,307);
$z[5]=Array("sourcerule","",307,342);
$z[6]=Array("bodyrule","<div class=\"content\">[内容]</div>",342,408);
$z[7]=Array("fyrule","<span class='current'><u></u>[内容]<u></u>4</a>",408,484);

?>