<?php
$z[0]=Array("charset","utf-8",0,34);
$z[1]=Array("list","http://www.chinacaipu.com/menu/qinleishipu/index_2.html",34,112);
$z[2]=Array("page","http://www.chinacaipu.com/menu/qinleishipu/(*).html",112,186);
$z[3]=Array("titlerule","<h1 class=\"contit\">[内容]</h1>",186,251);
$z[4]=Array("authorrule","",251,286);
$z[5]=Array("sourcerule","",286,321);
$z[6]=Array("bodyrule","<div class=\"content\">[内容]</div>",321,387);
$z[7]=Array("fyrule","<span class='current'><u></u>[内容]<u></u>下一页</a>\n        </div>",387,486);

?>