<?php
$z[0]=Array("charset","utf-8",0,34);
$z[1]=Array("list","http://www.chinacaipu.com/tags/1494/",34,93);
$z[2]=Array("page","http://www.chinacaipu.com/menu/teseshipin/(*).html",93,166);
$z[3]=Array("titlerule","<h1 class=\"contit\">[内容]</h1>",166,231);
$z[4]=Array("authorrule","",231,266);
$z[5]=Array("sourcerule","",266,301);
$z[6]=Array("bodyrule","<div class=\"content\">[内容]</div>",301,367);
$z[7]=Array("fyrule","<span class='current'><u></u>[内容]<u></u>4</a>",367,443);

?>