{dede:specnote imgheight='90' imgwidth='120'
                infolen='160' titlelen='60' col='1' idlist='1875,1758,1573,1570,1564'
                name='默认节点' noteid='default' isauto='1' rownum='10'
                keywords='' typeid='0'}
                <li><span class="date">[field:typename/]</span><a href="[field:arcurl /]" target="_blank">[field:title /]</a></li>
                {/dede:specnote}
