<?php
$z[0]=Array("charset","utf-8",0,34);
$z[1]=Array("list","http://www.chinacaipu.com/menu/huoguodiliaojipeifang",34,109);
$z[2]=Array("page","http://www.chinacaipu.com/menu/huoguodiliaojipeifang/(*).html",109,193);
$z[3]=Array("titlerule","<h1 class=\"contit\">[内容]</h1>",193,258);
$z[4]=Array("authorrule","<span class=\"info_txt\">作者：[内容]</a>",258,337);
$z[5]=Array("sourcerule","",337,372);
$z[6]=Array("bodyrule","<div class=\"content\">[内容]</div>",372,438);
$z[7]=Array("fyrule","<span class='current'><u></u>[内容]<u></u>4</a>",438,514);

?>