<li>[field:imglink/]<span>[field:title/]</span></a>
                    </ul>
        <div class="JQ-navwrap">
            <ul class="JQ-nav">
                                <li class="on"><a href="/menu/rouleishipu/70272.html"><img src="style/images/fcd8cd8dce419ffc3c2a62a8cb76ccc8.jpg" title="年糕红烧排骨"></a>
                                <li ><a href="/menu/rouleishipu/70278.html"><img src="style/images/smallf19fe00fbb382b91f2588eab9b45d1d61387768239.jpg" title="红萝卜焖牛肉"></a>
                                <li ><a href="/menu/hunanmeishi/70319.html"><img src="style/images/8b62bcef8f02ab850a0f967e7ee53bcd.jpg" title="干锅茶树菇"></a>
                                <li ><a href="/menu/sushishipu/70317.html"><img src="style/images/e6d964809b3c593d7fc9561ffb746e6c.jpg" title="干煸菜花"></a>
                                <li ><a href="/menu/rouleishipu/69899.html"><img src="style/images/b00e1d3032cc9bfb89c2da86af5ebfd2.jpg" title="葱烧大排"></a>
                                <li ><a href="/menu/rouleishipu/70248.html"><img src="style/images/small0b5af8a04c8d16ea42555763508d77441387437331.jpg" title="香辣羊排炖粉条"></a>
                            </ul>
        </div>
    </div>

    <div class="w380 mt20">

        <div class="jrcp"><h2>今日菜谱推荐</h2></div>

        <div class="cptj_l" id="cptj_l">

                                                <h3 class="cptj_tit">{dede:arclist flag='h' typeid='1' limit='0,1' titlelen='30'}	     

        <a href="[field:arcurl/]" target="_blank" title="[field:fulltitle/]">[field:title/]</a>