<li>[field:imglink/]<span>[field:title/]</span></a>
                    </ul>
        <div class="JQ-navwrap">
            <ul class="JQ-nav">{dede:arclist typeid=2 row=6  orderby=pubdate type='image.'}
                                <li class="on"> <a href="[field:arcurl/]">[field:image/]</a>
                            </ul>
        </div>
    </div>

    <div class="w380 mt20">

        <div class="jrcp"><h2>今日菜谱推荐</h2></div>

        <div class="cptj_l" id="cptj_l">

                                                <h3 class="cptj_tit">{dede:arclist flag='h' typeid='1' limit='0,1' titlelen='30'}	     

        <a href="[field:arcurl/]" target="_blank" title="[field:fulltitle/]">[field:title/]</a>