<?php
$z[0]=Array("array","@me = (empty(@me['litpic']) ? \"\" : \"<a href='{@me['arcurl']}' class='preview'><img src='{@me['litpic']}'/></a>\"); ",291,445);
$z[0][4]['runphp']="yes";
$z[1]=Array("typelink","",456,473);
$z[2]=Array("arcurl","",488,503);
$z[3]=Array("title","",519,533);
$z[4]=Array("pubdate","",582,628);
$z[4][4]['function']="GetDateTimeMK(@me)";
$z[5]=Array("click","",653,667);
$z[6]=Array("scores","",692,707);
$z[7]=Array("description","",740,760);

?>