<?php
$z[0]=Array("charset","utf-8",0,34);
$z[1]=Array("list","http://www.chinacaipu.com/menu/xinli/",34,94);
$z[2]=Array("page","http://www.chinacaipu.com/menu/xinli/(*).html",94,162);
$z[3]=Array("titlerule","<h1 class=\"contit\">[内容]</h1>",162,227);
$z[4]=Array("authorrule","<span class=\"info_txt\">作者：[内容]</a>",227,306);
$z[5]=Array("sourcerule","",306,341);
$z[6]=Array("bodyrule","<div class=\"content\">[内容]</div>",341,407);
$z[7]=Array("fyrule","<span class='current'><u></u>[内容]<u></u>4</a>",407,483);

?>