document.writeln("<script type=\"text/javascript\">");
document.writeln("     document.write(\'<a style=\"display:none!important\" id=\"tanx-a-mm_10010138_2401210_14726861\"></a>\');");
document.writeln("     tanx_s = document.createElement(\"script\");");
document.writeln("     tanx_s.type = \"text/javascript\";");
document.writeln("     tanx_s.charset = \"gbk\";");
document.writeln("     tanx_s.id = \"tanx-s-mm_10010138_2401210_14726861\";");
document.writeln("     tanx_s.async = true;");
document.writeln("     tanx_s.src = \"http://p.tanx.com/ex?i=mm_10010138_2401210_14726861\";");
document.writeln("     tanx_h = document.getElementsByTagName(\"head\")[0];");
document.writeln("     if(tanx_h)tanx_h.insertBefore(tanx_s,tanx_h.firstChild);");
document.writeln("</script>");