<?php  exit();
/*
Page: /dede/makehtml_homepage.php
Error: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ') And  arc.arcrank > -1    ORDER BY arc.sortrank desc  LIMIT 1,3' at line 6 <br />Error sql: <font color='red'>SELECT arc.*,tp.typedir,tp.typename,tp.corank,tp.isdefault,tp.defaultname,tp.namerule,
        tp.namerule2,tp.ispart,tp.moresite,tp.siteurl,tp.sitepath
        
        FROM `chihuo_archives` arc LEFT JOIN `chihuo_arctype` tp on arc.typeid=tp.id
        
         WHERE  FIND_IN_SET('c', arc.flag)>0  And  arc.typeid IN () And  arc.arcrank > -1    ORDER BY arc.sortrank desc  LIMIT 1,3 </font>
Time2014-01-04 14:13:01
*/
?>
<?php  exit();
/*
Page: /dede/makehtml_homepage.php
Error: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ') And  arc.channel = '1'  And  arc.arcrank > -1    ORDER BY arc.sortrank desc  L' at line 6 <br />Error sql: <font color='red'>SELECT arc.*,tp.typedir,tp.typename,tp.corank,tp.isdefault,tp.defaultname,tp.namerule,
        tp.namerule2,tp.ispart,tp.moresite,tp.siteurl,tp.sitepath
        ,addf.body
        FROM `chihuo_archives` arc LEFT JOIN `chihuo_arctype` tp on arc.typeid=tp.id
         LEFT JOIN `chihuo_addonarticle` addf ON addf.aid = arc.id 
         WHERE  FIND_IN_SET('p', arc.flag)>0  And  FIND_IN_SET('c', arc.flag)>0  And  arc.typeid IN () And  arc.channel = '1'  And  arc.arcrank > -1    ORDER BY arc.sortrank desc  LIMIT 0,1 </font>
Time2014-01-04 14:13:01
*/
?>
<?php  exit();
/*
Page: /dede/makehtml_homepage.php
Error: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ') And  arc.arcrank > -1    ORDER BY arc.sortrank desc  LIMIT 1,3' at line 6 <br />Error sql: <font color='red'>SELECT arc.*,tp.typedir,tp.typename,tp.corank,tp.isdefault,tp.defaultname,tp.namerule,
        tp.namerule2,tp.ispart,tp.moresite,tp.siteurl,tp.sitepath
        
        FROM `chihuo_archives` arc LEFT JOIN `chihuo_arctype` tp on arc.typeid=tp.id
        
         WHERE  FIND_IN_SET('c', arc.flag)>0  And  arc.typeid IN () And  arc.arcrank > -1    ORDER BY arc.sortrank desc  LIMIT 1,3 </font>
Time2014-01-04 14:14:07
*/
?>
<?php  exit();
/*
Page: /dede/makehtml_homepage.php
Error: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ') And  arc.channel = '1'  And  arc.arcrank > -1    ORDER BY arc.sortrank desc  L' at line 6 <br />Error sql: <font color='red'>SELECT arc.*,tp.typedir,tp.typename,tp.corank,tp.isdefault,tp.defaultname,tp.namerule,
        tp.namerule2,tp.ispart,tp.moresite,tp.siteurl,tp.sitepath
        ,addf.body
        FROM `chihuo_archives` arc LEFT JOIN `chihuo_arctype` tp on arc.typeid=tp.id
         LEFT JOIN `chihuo_addonarticle` addf ON addf.aid = arc.id 
         WHERE  FIND_IN_SET('p', arc.flag)>0  And  FIND_IN_SET('c', arc.flag)>0  And  arc.typeid IN () And  arc.channel = '1'  And  arc.arcrank > -1    ORDER BY arc.sortrank desc  LIMIT 0,1 </font>
Time2014-01-04 14:14:07
*/
?>
